credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: 'СЮДА_ТВОЙ_ПЕРВЫЙ_ЗАШИФРОВАННЫЙ_ПАРОЛЬ'
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: 'СЮДА_ТВОЙ_ВТОРОЙ_ЗАШИФРОВАННЫЙ_ПАРОЛЬ'
cookie:
  expiry_days: 30
  key: 'abcdefg_123456'  # Просто случайный набор символов
  name: 'analytics_cookie'
