credentials:
  usernames:
    jsmith:
      email: jsmith@example.com
      name: John Smith
      password: '$2b$12$E9/V5sJ2i.w.2sCgS3h8h.9yL5a2C/jS4.iG5eF2bB4E7k6f2a7y.'
    rdoe:
      email: rdoe@example.com
      name: Rebecca Doe
      password: '$2b$12$F1gH2i3j4k5L6m7n8o9p0u2v3w4x5y6z7A8B9C0D1E2F3G4H5I6J'
cookie:
  expiry_days: 30
  key: 'a_truly_random_secret_key_12345'
  name: 'analytics_cookie'
